### ISSUE TITLE
Better support for user-specific classes in data types

### ISSUE THREAD

**Issue by SebastianGB** [DLR-RM/RAFCON#11]
The user should be able to specify certain modules on RAFCON startup, which can be accessed inside the data_type field of data ports.

Currently this is possible via plugins, but a config entry would be nicer.

**Comment by franzlst** [comment]
You don't need a plugin. It is sufficient to have the module within the `PYTHONPATH`.

**Comment by SebastianGB** [comment]
Awesome! Couldn't remember that we already have this feature implemented (actually since quite some time xD).
