### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by adamwtow** [DLR-RM/RAFCON#2]
I'm wondering if you are still intending to release RAFCON?

**Comment by franzlst** [comment]
Hi @adamwtow,

we still plan to make RAFCON OpenSource. Yet, we need to clarify some internal stuff before.

Please contact us via rafcon@dlr.de for your specific use case.

**Comment by Rbelder** [comment]
So finally RAFCON is now Open Source. It is available on GitHub (https://github.com/DLR-RM/RAFCON), PyPi (pip install rafcon), Read the Docs (http://rafcon.readthedocs.io/en/latest/) and has its own homepage (https://DLR-RM.github.io/RAFCON/). The homepage and the documentation are getting there finishing while the next days but everything is online and can be used.

**Comment by stoertebeker23** [comment]
Nice!

**Comment by uservinu** [comment]
Great News. Congratulations Y'all:+1: :100:
