### ISSUE TITLE
program icon in task bar missing since version 0.13.x

### ISSUE THREAD

**Issue by SebastianGB** [DLR-RM/RAFCON#20]
Since version 0.13.x the RAFCON icon in the task bar is missing.

**Comment by SebastianGB** [comment]
Probably this is related to gtk3.

**Comment by franzlst** [comment]
Fixed with 0dc30c37c37bea01924855fd8256f3ffb69d8a18 and will be part of the next release.

The error only occured, it RAFCON was _not_ installed via `pip`.
