### ISSUE TITLE
Suggestion: Do not store semantic data if not available

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#21]
When a state machine is saved, for each state a `semantic_data.json` file is created. Even, if there is no semantic data (which is probably the case in over 95% of the times).

These empty (`{}`) files are then usually versioned and need to be loaded with the state machine.

Therefore, I would suggest to only create this file, if a state contains semantic data.

Is there anything against this @SebastianGB?

**Comment by sebastian-brunner** [comment]
This is good suggestion. We can add this feature.

**Comment by franzlst** [comment]
Fixed in 30ffae4113bf87db7547b73e7fa5f4a50520c4fb
