### ISSUE TITLE
How to move the RAFCON window in Gnome3 on Ubuntu 18.04?

### ISSUE THREAD

**Issue by SebastianGB** [DLR-RM/RAFCON#3]
How can I move the RAFCON window in Gnome3 on Ubuntu 18.04?

**Comment by franzlst** [comment]
With RAFCON [0.13.0](https://github.com/DLR-RM/RAFCON/releases/tag/0.13.0), this workaround is no longer necessary. Just use the TitleBar/HeaderBar to move the RAFCON window.
