### ISSUE TITLE
Contributing guidelines not easily accessible

### ISSUE THREAD

**Issue by nickswalker** [DLR-RM/RAFCON#32]
GitHub displays lots of helpful prompts for new contributors, but clicking on them is likely to confuse users because they just point to the CONTRIBUTING symlink. Perhaps a compiled version of this file could be put there instead to improve the new contributor experience?
![Screenshot from 2020-02-07 17-23-27](https://user-images.githubusercontent.com/924295/74076960-e1e30c00-49d0-11ea-9dde-2a6a9a18bf6b.png)
![Screenshot from 2020-02-07 17-22-37](https://user-images.githubusercontent.com/924295/74076961-e1e30c00-49d0-11ea-9d1c-c48ff372760a.png)
![Screenshot from 2020-02-07 17-42-52](https://user-images.githubusercontent.com/924295/74077023-4c944780-49d1-11ea-9183-32184485c52d.png)

**Comment by franzlst** [comment]
Hi @nickswalker, thank you for the hint! Unfortunately, GitHub cannot follow symlinks and only displays the path to the target document. This is indeed not very helpful for a user.

I don't want to have the same information twice in the repository, but maybe it would be an idea to turn the symlink around, i.e. have the actual document in the root and only a link in the documentation. I need to see, whether Sphinx can handle that.

**Comment by franzlst** [comment]
Fixed in af2e26805e9ce7d8a1942270b087f224b9ef5e6b
