### ISSUE TITLE
Rafcon crashes during 2ButtonDialog

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#352]
Just now rafcon crashed while executing a 2ButtonDialog:

![screenshot from 2017-05-24 11-49-31](https://rmc-github-server/storage/user/23/files/ab829406-4077-11e7-9a0e-c864b8208c02)

Does not happen every time. 

Originally created by @peter-lehner  at 2017-05-24 09:54:16+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
Original issue can not be identified
