### ISSUE TITLE
Visualization mode: Data flows for selected state only

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#377]
A visualization mode, where only the data flows of the currently selected state is shown, would highly improve the overview for complex state machines.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-07-19 08:14:29+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
Duplicate of https://github.com/DLR-RM/RAFCON/discussions/937
