### ISSUE TITLE
How to set default value of custom data type?

### ISSUE THREAD

**Issue by lx852357** [DLR-RM/RAFCON#38]
I create a custom data type like this:
```
import json

class Point:
  def __init__(self,px=0,py=0):
    self.x = px
    self.y = py

  def toJSON(self):
    return json.dumps(self,default=lambda o:o.__dict__,sort_keys=True,indent=4)
```

**State source:**
```
def execute(self, inputs, outputs, gvm):
    point = inputs['point']
    self.logger.info("[{}, {}]".format(point.x,point.y))
    return 0
```
**Input Ports:**
![image](https://user-images.githubusercontent.com/20334928/77289453-03aa0100-6ca8-11ea-824e-1b00cedf5c8c.png)

**Console output:**
![image](https://user-images.githubusercontent.com/20334928/77289516-276d4700-6ca8-11ea-9d11-69eae11deff3.png)

The default value will be directly mapped to point.x. 
When I set "`[1,0]`" as default value the output is "`INFO - test: [[1,0], 0]`". The same for others.

**Comment by sebastian-brunner** [comment]
Hi @lx852357, 
currently we don't support the setting of default values for custom data types, only primitive data types such as float, list, dict, string, tuple etc.

You can create a small generator state which creates the data as you want.

**Comment by sebastian-brunner** [comment]
An enhancement on our side would be to accept e.g. a list for the default values and create an object of the given class by using the elements in that list for the constructor parameters.

**Comment by franzlst** [comment]
Well, there is at least _rudimentary_ support for parsing default values into custom types. Have a look [at the code responsible for the conversion](https://github.com/DLR-RM/RAFCON/blob/master/source/rafcon/utils/type_helpers.py#L73). In case of a custom class, the function tries to call the constructor of the class with the default value passed as string. Therefore, you can do something like this:

```python
import json

class Point:
  def __init__(self,px=0,py=0):
    if isinstance(px, str):
        self.x, self.y = my_str2point_parser(px)
    else:
        self.x = px
        self.y = py
```

Note: I have never tested this!

**Comment by lx852357** [comment]
Thank you!

**Comment by franzlst** [comment]
Did it work?

**Comment by lx852357** [comment]
Yes, it worked correctly！
```
import json
class Point:
    def __init__(self,px=0,py=0):
        if isinstance(px,str):
            self.x,self.y = self.str2point_parser(px)
        else:
            self.x = px
            self.y = py
    def toJSON(self):
        return json.dumps(self, default=lambda o: o.__dict__, 
            sort_keys=True, indent=4)

    def str2point_parser(self,px): # “10，100”
        point = px.split(",")
        return int(point[0]), int(point[1])

```

**Comment by franzlst** [comment]
Cool, thx!

**Comment by sebastian-brunner** [comment]
@franzlst: nice idea btw.! At least, this works for data types were you have own control of (i.e. not for default ros types).
