### ISSUE TITLE
Names of data ports/outcomes too big

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#381]
See image

![size_bug](https://rmc-github-server/storage/user/35/files/dd894ffa-6c5d-11e7-90c7-5d8800829c35)

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-07-19 08:40:44+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
What do you suggest here?

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2017-07-19 09:35:46+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
No concrete description
