### ISSUE TITLE
Successfully loaded plugin but not available.

### ISSUE THREAD

**Issue by lx852357** [DLR-RM/RAFCON#39]
My plugin path: `/home/bot/rafcon_plugins/templates`.(download from this repo/master)
The fold like this:
![image](https://user-images.githubusercontent.com/20334928/77412513-f9f9c980-6d8b-11ea-8c8a-1cbee153ccdf.png)

While set the **RAFCON_PLUGIN_PATH**=`/home/bot/rafcon_plugins/templates`.

An error reported:`ERROR - rafcon.utils.plugins:  The specified plugin path does not exist: /home/bot/rafcon_plugins/template`.

When set **RAFCON_PLUGIN_PATH**=`/home/bot/rafcon_plugins/` the message is:
 `2020-03-24 16:16:42:     INFO - rafcon.utils.plugins:  Found plugin 'rafcon_plugins' at /home/bot/rafcon_plugins/`
`2020-03-24 16:16:42:     INFO - rafcon.utils.plugins:  Successfully loaded plugin 'rafcon_plugins'
`

But it does't call hooks.py because I have not seen this [message](https://github.com/DLR-RM/RAFCON/blob/master/share/rafcon/examples/plugins/templates/hooks.py#L15).

And the tutorial said put `xxx/plugins/templates` into **RAFCON_PLUGIN_PATH** instead of `xxx/plugins`.
![image](https://user-images.githubusercontent.com/20334928/77410553-07618480-6d89-11ea-8650-761f4c807344.png)

Besides, I found [that](https://github.com/DLR-RM/RAFCON/blob/master/source/rafcon/utils/plugins.py#L43).

I have a test.

**Test code:**
```
import os 

path1 = '/home/bot/rafcon_plugins/templates'
isExist = os.path.exists(path) 
print(isExist) 
  
path2 = '/home/bot/rafcon_plugins/templates/hooks.py'
isExist = os.path.exists(path) 
print(isExist) 

path2 = '/home/bot/rafcon_plugins'
isExist = os.path.exists(path) 
print(isExist) 
```
Outputs:
```
False
True
True
```

Is something wrong with me?

**Comment by franzlst** [comment]
`RAFCON_PLUGIN_PATH` should be set to `/home/bot/rafcon_plugins/templates`. If you didn't make a cop'n'paste error, then you forget the 's':
`ERROR - rafcon.utils.plugins: The specified plugin path does not exist: /home/bot/rafcon_plugins/template` <= No 's' at the end

**Comment by lx852357** [comment]
Sorry, it is my fault.......
