### ISSUE TITLE
enhance support for library replacement

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#391]
Sometimes developers have no write access to libraries they use (esp. if they are released). If another library inside such a library changes its name or location the user is asked to show RAFCON where the original library has gone. By selecting the new library it is loaded but only replaced temporary (even after a save command is issued).

A warning would be great to inform the user that the replacement he just did is only temporary because of missing privileges.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-08-21 05:42:39+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
Cannot reproduce this, if a new state location is selected, it will be saved accordingly
