### ISSUE TITLE
Search for all library usages

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#542]
# Use Case:

In common IDEs the user can search for the usages of functions. This would also be nice for libraries in RAFCON.

Based on this, the user could replace the occurrence of one library with another library having the same interface, i.e. input and output ports. => separate issue

# Technical TODOs:
* create a new widget in which the search results can be visualized; therefore create a new tab in the left sidebar (or in bottom bar)
* create a new entry in the right-click-menu of a library state to search for usages
* order the elements in the results widget in a tree-view
* all the leaf-elements of the results tree-view should have the same right-click-menu as the library in the LibraryManager tab (in the left sidebar)

# Further reading:
* https://github.com/DLR-RM/RAFCON/issues/351

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-05-29 05:28:49+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Based on this the user could replace the occurrence of one library with another library having the same interface (i.e. input and output ports).

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-05-29 05:29:29+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Yes that issue we have had already very early #35 and and later again #351. And we discussed already what kind of features we could full-fill with a proper search and replace widget.

Originally created by @Rbelder  at 2018-05-29 14:29:19+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I created a project "Search Widget" to track our efforts for this kind of features and there discussion.
 

Originally created by @Rbelder  at 2018-05-30 14:17:56+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
Implemented in 0.14.11
