### ISSUE TITLE
If a child state type change of a parent with self-transition is undone gaphas fails

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#594]
This is a very specific bug so it can be seen as low priority.

Reproduction procedure:
- new state machine
- add hierarchy state to root state `X`
- add self transition from outcome to income of new hierarchy state `Y`
- add a state `Z` inside of the new hierarchy state
- change the type of this new state with path `X/Y/Z`
- try to undo this operation by e.g. pressing `Control-Z`

The crash will say:
```
    bounds, data, clipped_bounds = self._ids[item]
KeyError: <rafcon.gui.mygaphas.items.connection.TransitionView object at 0x7f36a2dc8450>
```
and then

```
    return sorted(nodes, key=attrgetter(index_key), reverse=reverse)
AttributeError: 'TransitionView' object has no attribute '_canvas_index'
```

I think the major problem is in the `adapt_complex_action` method of the controller.

Originally created by @Rbelder  at 2018-08-31 12:55:14+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
cannot reproduce
