### ISSUE TITLE
Show library name in external execution history viewer

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#766]
Show the library_state.name (i.e. the user defined name for his library instantiation) for a library state in external execution history viewer not the library_state.library_name (i.e. the name of the library)

Therefore also see https://rmc-github-server/sebastian-brunner/rafcon_internal_data/blob/master/documentation/glossary.md

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-07-25 14:17:03+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
With the upcoming release, users can simply open the state machine from the execution history
