### ISSUE TITLE
Entry and exit actions for States

### ISSUE THREAD

**Issue by amitabhn** [DLR-RM/RAFCON#8]
Does rafcon support definitions of entry and exit actions, especially for Hierarchical States?

**Comment by franzlst** [comment]
Hi @amitabhn, 

despite a very early version of RAFCON included entry and exit scripts for `HierarchicyState`s, we decided to remove these purposely.

In our experience, most of the time those scripts are not needed, as `HierarchyState`s often only fulfill a (semantic) grouping purpose.

If you still need these scripts, you can realize them via `ExecutionState`s at the beginning and end of the `HierarchyState`.

May I ask you what your purpose is?

**Comment by amitabhn** [comment]
I am trying to build a state machine for a reactive system which can have asynchronous external events to trigger state transitions, based on the principles explained in Miro Samek's book Practical UML Statecharts in C/C++: Event-Driven Programming for Embedded Systems.

Some of the concepts mentioned are very helpful in state machine design, notably state entry and exit actions (especially for safety aspects), state specific actions of async events, propagation of async events to superstates till it is not handled, trigger specific actions, event deferral, pseudostates, etc.

I was hoping to find an intuitive implementation for the same in python and which also preferably supports easy integration with ROS.

> If you still need these scripts, you can realize them via `ExecutionState`s at the beginning and end of the `HierarchyState`.

Not sure whether this approach would be compliant with the transition execution sequence of an HSM (evaluation of guard condition; exit actions of all nested states; trigger action; entry actions of nested states)

**Comment by franzlst** [comment]
One general issue that might arise for your problem together with RAFCON is that RAFCON is not event-driven. If you are interested in the details behind some design decision, I can recommend you [our paper about RAFCON](https://elib.dlr.de/112067/).
