### ISSUE TITLE
Provide generic libraries for ROS and LN

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#829]
To speed up the development of state-machines and ease the integration with other systems, generic libraries for at least ROS and LN would be helpful.

ROS libraries could include sending and receiving of topics, running services, action clients, etc.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2016-01-18 12:22:44+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
Internal RMC problem, removing therfore
