### ISSUE TITLE
Focus per doubleclick

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#833]
It would be useful to set the focus in the graphical editor to a state, that is double clicked in the state machine tree.

insert by @Rbelder on 2016-11-11
**Example1:** if a scoped variable is double clicked in the graphical editor widget the scoped variable in the state editor should be selected and the tab scope_data_port-list-view set to the current_page in respective notebook.
**Example2:** If a state is double-clicked in the state-machine-tree-view the state becomes focused/centered in the graphical editor/viewer.

Major sub-task is:
- [x] introduce a focus flag in the selection maybe best implemented by a signal.

other sub-tasks are copy'n'paste from issue #76 and suit this issue more

Please complete the following list of behavior pattern (sub-tasks) resulting from forced selection (double-click) -> the respective force-flag could be meta-signal:
- [ ] forced-selection of a single data flow (source: graphical-editor or data-flow-list) results in selection in the following widgets
  - [x] respective row in data-flow-list and respective tab of the widget
  - [ ] respective data-flow in graphical editor
- [ ] forced-selection of a single scoped-, input-, output-data-port  (source: graphical-editor or respective list-widget -> overview-widget, too) results in selection in the following widgets
  - [ ] respective row in data-port-list-widget and respective tab of the widget
    - [x] input port
    - [ ] output port
    - [ ] scoped variable
  - [ ] respective data-port-element in graphical editor
    - [ ] input port
    - [ ] output port
    - [ ] scoped variable
- [ ] forced-selection of a single transition (source: graphical-editor or transition-list) results in selection in the following widgets
  - [x] respective row in transition-list and respective tab of the widget
  - [ ] respective transition in graphical editor
- [ ] forced-selection of a single outcome (source: graphical-editor or outcome-list-widget -> overview-widget, too) results in selection in the following widgets
  - [x] respective row in outcome-list-widget and respective tab of the widget
  - [ ] respective outcome in graphical editor
- [ ] forced-selection of a single state (source: graphical-editor or state-machine-tree-list) results in selection in the following widgets
  - [x] respective row in state-machine-tree-list
  - [ ] respective state in graphical editor

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-01-20 06:34:59+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
Already implemented
