### ISSUE TITLE
error message when locking gvm variable in ROS subcriber callback function

### ISSUE THREAD

**Issue by jeffRowley321** [DLR-RM/RAFCON#855]
in an execution state a subscriber is located which is calling a callback function  and inside the callback function I want to lock a variable because this variable should also be accessed from other states.

This is the code so far:

```
def execute(self, inputs, outputs, gvm):
    # ... some init code:
	global var_to_lock
	global access
	access = 0

	var_to_lock = gvm.get_variable("key", per_reference=True, access_key=access)
	subscriber = rospy.Subscriber("/something/to/subscribe", Int32, subscriber_callback)

	r = rospy.Rate(10)
	while not rospy.is_shutdown():
	    # ... other code


def subscriber_callback(msg):
    # ... some init code:
    global var_to_lock
    global access
    
    # locking:
    access = gvm.lock_variable("key") # also tried var_to_lock here instead "key"

    var_to_lock = msg.data
    
    # unlocking:
    gvm.unlock_variable("key", access) # also tried var_to_lock here instead "key"
```

But I get this error message:
`Name error: name gvm is not defined`

the error references to the line where I have:
`access = gvm.lock_variable("key")`

Please help.

**Comment by franzlst** [comment]
In the function `subscriber_callback`, you do not have access to the variable `gvm`. You need to get a referenc to this object. This can be done using:

```python
from rafcon.core.singleton import global_variable_manager as gvm
```

The usage of global variables is a bit hacky here. An alternative solution would be to bind the variables to the subscriber using `functools.partial`:

```python
# in execute():
from functools import partial
subscriber_cb = partial(subscriber_callback, variable=var_to_look, key=access)
subscriber = rospy.Subscriber("/something/to/subscribe", Int32, subscriber_cb)

# ...
def subscriber_callback(msg, variable, key):
# ...
```

**Comment by sebastian-brunner** [comment]
Closing, as of inactivity. Please reopen if there are any further questions.
