### ISSUE TITLE
Error when launching rafcon

### ISSUE THREAD

**Issue by shafiqazam** [DLR-RM/RAFCON#859]
Hello,

I just installed rafcon on my Ubuntu 20.04. When I tried to launch it, there is an error which I have attached below. I have followed your installation guide step by step. 

![error_rafcon](https://user-images.githubusercontent.com/72918857/146534402-50a57125-2295-44d2-849e-004483d5553d.jpg)

Thank you in advance for your answers

**Comment by franzlst** [comment]
This has already been reported in https://github.com/DLR-RM/RAFCON/issues/852

Can you check whether the solution from there also helps in your case?

**Comment by sebastian-brunner** [comment]
Closing due to inactiveness. Please reopen if requried.
