### ISSUE TITLE
Error import external library (ROS2)

### ISSUE THREAD

**Issue by Hytac** [DLR-RM/RAFCON#870]
Hi, I have a working ros2 package with all the interfaces for actions and services.
I want to call a service/action from a rafcon ExecutionState, its working fine with interfaces that are already define in ros2 such as (std_msgs/String.msg) but i can not make it work with my custom interfaces.

When i try to import the library in my python code i get the following error:

`2022-09-16 05:00:49:    DEBUG - rafcon.gui.controllers.state_editor.source_editor:  Parsing execute script...
[
    {
        "type": "error",
        "module": "file_to_get_pylinted",
        "obj": "",
        "line": 8,
        "column": 0,
        "path": "/tmp/rafcon-usr/4068/tmpaz0by0k4/file_to_get_pylinted.py",
        "symbol": "import-error",
        "message": "Unable to import 'SetRGB'",
        "message-id": "E0401"
    }
]
`

This is where my library is located:
![image](https://user-images.githubusercontent.com/60785987/190643015-36e782b4-42a3-4ed9-99fe-2ad2a485b828.png)

I have added my library to rafcon like this:
![image](https://user-images.githubusercontent.com/60785987/190643186-22976a28-e7c7-49cc-bf3c-fae5db8846c5.png)

My ExecutionState code looks like this:
![image](https://user-images.githubusercontent.com/60785987/190643525-8eb054d3-e81c-4b58-8cfd-a526a91731c7.png)

**Comment by franzlst** [comment]
I'm not so into ROS 2, but in general when you have import errors, you need to make sure your `PYTHONPATH` env var is properly set up. In your case, the  `PYTHONPATH` need to contain the parent folder of `action_server_interfaces`.

However, in your case it complains about not finding `SetRGB` class and not about missing `action_server_interfaces` module. So maybe the import path is wrong?

> I have added my library to rafcon like this:

This config is for adding RAFCON libraries, not for adding Python packages.

**Comment by sebastian-brunner** [comment]
Closing due to inactiveness. Please reopen if requried.
